/**
 * Minimal seed data for an ephemeral demo session.
 * Lives entirely in memory — never touches the database.
 */

const now = new Date();
const isoNow = now.toISOString();
const inDays = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString();
};
const dateOnly = (n: number) => inDays(n).slice(0, 10);

export const buildSeed = () => {
  const containerId = "demo-container-1";

  const containers = [
    {
      id: containerId,
      box_number: "BOX-001",
      box_number_alt: null,
      cache_box_type: "Storage Box",
      status_cache_box: "Available",
      barcode: "DEMO-BOX-001",
      box_description: "Main field kit",
      x_group_display: "Demo Group",
      section_id: null,
      container_type_id: null,
      container_status_id: null,
      container_group_id: null,
      custom_data: null,
      item_count: 3,
      created_at: isoNow,
      updated_at: isoNow,
      created_by: null,
    },
  ];

  const assets = [
    {
      id: "demo-asset-1",
      description: "Generator 5kW",
      subcategory: "Power",
      section: "A1",
      quantity_available: 4,
      quantity_out: 1,
      status_item: "Available",
      date_expire: null,
      id_cache_fema: "REF-1001",
      id_cache_tf: null,
      barcode: "DEMO-1001",
      serial_number: "SN-1001",
      manufacturer: "Honda",
      model_part_num: "EU5000",
      group_abbv: "PWR",
      group_year: 2024,
      is_internal: false,
      image_url: null,
      low_stock_threshold: 2,
      critical_stock_threshold: 1,
      container_id: containerId,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
    {
      id: "demo-asset-2",
      description: "Hard Hat",
      subcategory: "PPE",
      section: "B2",
      quantity_available: 25,
      quantity_out: 5,
      status_item: "Available",
      date_expire: null,
      id_cache_fema: "REF-1002",
      id_cache_tf: null,
      barcode: "DEMO-1002",
      serial_number: null,
      manufacturer: "MSA",
      model_part_num: "V-Gard",
      group_abbv: "PPE",
      group_year: 2024,
      is_internal: false,
      image_url: null,
      low_stock_threshold: 10,
      critical_stock_threshold: 5,
      container_id: containerId,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
    {
      id: "demo-asset-3",
      description: "Radio Handheld",
      subcategory: "Comms",
      section: "C1",
      quantity_available: 8,
      quantity_out: 2,
      status_item: "In Use",
      date_expire: null,
      id_cache_fema: "REF-1003",
      id_cache_tf: null,
      barcode: "DEMO-1003",
      serial_number: "SN-1003",
      manufacturer: "Motorola",
      model_part_num: "XPR7550",
      group_abbv: "COM",
      group_year: 2023,
      is_internal: false,
      image_url: null,
      low_stock_threshold: 3,
      critical_stock_threshold: 1,
      container_id: containerId,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
    {
      id: "demo-asset-4",
      description: "First Aid Kit",
      subcategory: "Medical",
      section: "D1",
      quantity_available: 6,
      quantity_out: 0,
      status_item: "Available",
      date_expire: dateOnly(180),
      id_cache_fema: "REF-1004",
      id_cache_tf: null,
      barcode: "DEMO-1004",
      serial_number: null,
      manufacturer: "Adventure Medical",
      model_part_num: "Pro-1",
      group_abbv: "MED",
      group_year: 2024,
      is_internal: false,
      image_url: null,
      low_stock_threshold: 3,
      critical_stock_threshold: 1,
      container_id: null,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
    {
      id: "demo-asset-5",
      description: "Chainsaw",
      subcategory: "Tools",
      section: "A2",
      quantity_available: 3,
      quantity_out: 1,
      status_item: "Under Service",
      date_expire: null,
      id_cache_fema: "REF-1005",
      id_cache_tf: null,
      barcode: "DEMO-1005",
      serial_number: "SN-1005",
      manufacturer: "Stihl",
      model_part_num: "MS-261",
      group_abbv: "TOOL",
      group_year: 2023,
      is_internal: false,
      image_url: null,
      low_stock_threshold: 2,
      critical_stock_threshold: 1,
      container_id: null,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
    {
      id: "demo-asset-6",
      description: "Water Pump",
      subcategory: "Equipment",
      section: "B1",
      quantity_available: 2,
      quantity_out: 0,
      status_item: "Available",
      date_expire: null,
      id_cache_fema: "REF-1006",
      id_cache_tf: null,
      barcode: "DEMO-1006",
      serial_number: "SN-1006",
      manufacturer: "Honda",
      model_part_num: "WB20",
      group_abbv: "EQP",
      group_year: 2024,
      is_internal: false,
      image_url: null,
      low_stock_threshold: 1,
      critical_stock_threshold: 1,
      container_id: null,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
  ];

  const requirements = [
    {
      id: "demo-req-1",
      name: "CPR Certification",
      requirement_type: "Certification",
      validity_period_days: 730,
      is_active: true,
      description: "Valid CPR certification",
      created_at: isoNow,
      updated_at: isoNow,
    },
    {
      id: "demo-req-2",
      name: "Forklift Operator License",
      requirement_type: "License",
      validity_period_days: 1095,
      is_active: true,
      description: "Forklift operator certification",
      created_at: isoNow,
      updated_at: isoNow,
    },
  ];

  const employees = [
    {
      id: "demo-emp-1",
      first_name: "Alex",
      last_name: "Morgan",
      email: "alex@example.com",
      phone: "555-0101",
      position: "Field Lead",
      department: "Operations",
      department_id: null,
      status: "Active",
      employee_status_id: null,
      hire_date: dateOnly(-365),
      avatar_url: null,
      base_location: "HQ",
      employee_id: "EMP-001",
      fema_id: null,
      notes: null,
      tags: null,
      role_id: null,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
      requirements_stats: { compliant: 2, expiring_soon: 0, missing_expired: 0, total: 2 },
      employee_requirements: [] as any[],
      team_role: null,
    },
    {
      id: "demo-emp-2",
      first_name: "Jordan",
      last_name: "Lee",
      email: "jordan@example.com",
      phone: "555-0102",
      position: "Technician",
      department: "Maintenance",
      department_id: null,
      status: "Active",
      employee_status_id: null,
      hire_date: dateOnly(-200),
      avatar_url: null,
      base_location: "HQ",
      employee_id: "EMP-002",
      fema_id: null,
      notes: null,
      tags: null,
      role_id: null,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
      requirements_stats: { compliant: 1, expiring_soon: 1, missing_expired: 0, total: 2 },
      employee_requirements: [] as any[],
      team_role: null,
    },
    {
      id: "demo-emp-3",
      first_name: "Sam",
      last_name: "Rivera",
      email: "sam@example.com",
      phone: "555-0103",
      position: "Coordinator",
      department: "Operations",
      department_id: null,
      status: "Active",
      employee_status_id: null,
      hire_date: dateOnly(-90),
      avatar_url: null,
      base_location: "Field",
      employee_id: "EMP-003",
      fema_id: null,
      notes: null,
      tags: null,
      role_id: null,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
      requirements_stats: { compliant: 0, expiring_soon: 0, missing_expired: 1, total: 1 },
      employee_requirements: [] as any[],
      team_role: null,
    },
    {
      id: "demo-emp-4",
      first_name: "Casey",
      last_name: "Park",
      email: "casey@example.com",
      phone: "555-0104",
      position: "Driver",
      department: "Logistics",
      department_id: null,
      status: "Active",
      employee_status_id: null,
      hire_date: dateOnly(-30),
      avatar_url: null,
      base_location: "Field",
      employee_id: "EMP-004",
      fema_id: null,
      notes: null,
      tags: null,
      role_id: null,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
      requirements_stats: { compliant: 1, expiring_soon: 0, missing_expired: 0, total: 1 },
      employee_requirements: [] as any[],
      team_role: null,
    },
  ];

  const employeeRequirements = [
    {
      id: "demo-er-1",
      requirement_id: "demo-req-1",
      employee_id: "demo-emp-1",
      status: "Compliant",
      issue_date: dateOnly(-100),
      expire_date: dateOnly(630),
      notes: null,
    },
    {
      id: "demo-er-2",
      requirement_id: "demo-req-2",
      employee_id: "demo-emp-1",
      status: "Compliant",
      issue_date: dateOnly(-200),
      expire_date: dateOnly(895),
      notes: null,
    },
    {
      id: "demo-er-3",
      requirement_id: "demo-req-1",
      employee_id: "demo-emp-2",
      status: "Compliant",
      issue_date: dateOnly(-300),
      expire_date: dateOnly(45),
      notes: null,
    },
    {
      id: "demo-er-4",
      requirement_id: "demo-req-2",
      employee_id: "demo-emp-3",
      status: "Expired",
      issue_date: dateOnly(-1200),
      expire_date: dateOnly(-30),
      notes: null,
    },
    {
      id: "demo-er-5",
      requirement_id: "demo-req-1",
      employee_id: "demo-emp-4",
      status: "Compliant",
      issue_date: dateOnly(-30),
      expire_date: dateOnly(700),
      notes: null,
    },
  ];

  const tasks = [
    {
      id: "demo-task-1",
      title: "Generator Maintenance",
      description: "Monthly generator service check",
      task_type: "service",
      priority: "high",
      status: "pending",
      start_date: dateOnly(2),
      end_date: dateOnly(2),
      start_time: "09:00",
      end_time: "11:00",
      assigned_employees: ["demo-emp-2"],
      location: "HQ",
      reminder_enabled: true,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
    {
      id: "demo-task-2",
      title: "Safety Training",
      description: "Quarterly safety briefing for the team",
      task_type: "training",
      priority: "medium",
      status: "pending",
      start_date: dateOnly(7),
      end_date: dateOnly(7),
      start_time: "13:00",
      end_time: "15:00",
      assigned_employees: ["demo-emp-1", "demo-emp-3"],
      location: "Conference Room",
      reminder_enabled: true,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
    {
      id: "demo-task-3",
      title: "Inventory Audit",
      description: "Full warehouse audit",
      task_type: "review",
      priority: "medium",
      status: "in_progress",
      start_date: dateOnly(0),
      end_date: dateOnly(1),
      start_time: "08:00",
      end_time: "17:00",
      assigned_employees: ["demo-emp-1"],
      location: "Warehouse A",
      reminder_enabled: false,
      user_id: null,
      created_at: isoNow,
      updated_at: isoNow,
    },
  ];

  return { assets, employees, requirements, employeeRequirements, tasks, containers };
};