import { PlacedCase } from "@/types/pallet-builder";

// Standard pallet size definitions - industry standard options
export const STANDARD_PALLET_SIZES = [
  { id: "gma-48x40", name: "GMA Standard (48×40)", width: 48, length: 40, maxWeight: 2500, description: "Most common US size" },
  { id: "gma-48x48", name: "Square (48×48)", width: 48, length: 48, maxWeight: 2800, description: "Square format" },
  { id: "euro-48x32", name: "Euro (48×32)", width: 48, length: 32, maxWeight: 2200, description: "European standard" },
  { id: "iso-42x42", name: "ISO (42×42)", width: 42, length: 42, maxWeight: 2000, description: "ISO standard" },
  { id: "half-48x20", name: "Half Pallet (48×20)", width: 48, length: 20, maxWeight: 1250, description: "Half-size option" },
  { id: "quarter-24x20", name: "Quarter (24×20)", width: 24, length: 20, maxWeight: 600, description: "Quarter pallet" },
];

// Pre-built sample layout with items arranged - cross-industry examples
export const SAMPLE_PALLET_CASES: PlacedCase[] = [
  // Layer 1 - Heavy/base items
  {
    id: "sample-case-1",
    caseId: "EQUIP-001",
    caseType: "Heavy Duty",
    x: 0,
    y: 0,
    z: 1,
    rotation: 0,
    width: 24,
    length: 20,
    height: 12,
    weight: 150,
    condition: "excellent",
    fragile: false,
    category: "Equipment",
  },
  {
    id: "sample-case-2",
    caseId: "EQUIP-002",
    caseType: "Heavy Duty",
    x: 24,
    y: 0,
    z: 1,
    rotation: 0,
    width: 24,
    length: 20,
    height: 12,
    weight: 140,
    condition: "good",
    fragile: false,
    category: "Equipment",
  },
  {
    id: "sample-case-3",
    caseId: "SUPPLY-001",
    caseType: "Standard",
    x: 0,
    y: 20,
    z: 1,
    rotation: 0,
    width: 16,
    length: 20,
    height: 10,
    weight: 200,
    condition: "good",
    fragile: false,
    category: "Supplies",
  },
  {
    id: "sample-case-4",
    caseId: "SUPPLY-002",
    caseType: "Standard",
    x: 16,
    y: 20,
    z: 1,
    rotation: 0,
    width: 16,
    length: 20,
    height: 10,
    weight: 200,
    condition: "good",
    fragile: false,
    category: "Supplies",
  },
  {
    id: "sample-case-5",
    caseId: "MISC-001",
    caseType: "Standard",
    x: 32,
    y: 20,
    z: 1,
    rotation: 0,
    width: 16,
    length: 20,
    height: 10,
    weight: 80,
    condition: "excellent",
    fragile: false,
    category: "Miscellaneous",
  },
  // Layer 2 - Medium items
  {
    id: "sample-case-6",
    caseId: "TECH-001",
    caseType: "Standard",
    x: 0,
    y: 0,
    z: 2,
    rotation: 0,
    width: 20,
    length: 16,
    height: 8,
    weight: 60,
    condition: "good",
    fragile: false,
    category: "Technology",
  },
  {
    id: "sample-case-7",
    caseId: "SUPPLY-003",
    caseType: "Standard",
    x: 20,
    y: 0,
    z: 2,
    rotation: 0,
    width: 16,
    length: 16,
    height: 8,
    weight: 45,
    condition: "good",
    fragile: false,
    category: "Supplies",
  },
  {
    id: "sample-case-8",
    caseId: "FRAGILE-001",
    caseType: "Protective",
    x: 0,
    y: 16,
    z: 2,
    rotation: 0,
    width: 24,
    length: 16,
    height: 10,
    weight: 75,
    condition: "excellent",
    fragile: true,
    category: "Fragile Items",
  },
];

export const SAMPLE_PALLET_CONFIG = {
  name: "Demo Pallet Layout",
  dimensions: { width: 48, length: 40 },
  maxWeight: 2500,
  description: "Pre-configured sample layout with mixed equipment and supplies",
};
