// Sample shipment data for demo purposes
export const SAMPLE_SHIPMENT = {
  destination: "Branch Office - West Campus",
  carrier: "Company Transport",
  transportType: "Ground",
  notes: "#StandardDelivery #OfficeSupplies - Monthly supply replenishment",
  specialInstructions: "Deliver to Loading Dock 3. Contact site coordinator upon arrival. Requires signature from authorized personnel.",
  pallets: [
    {
      id: "PLT-001",
      section: "A",
      totalWeight: 1250.5,
      totalVolume: 48.2,
      itemCount: 156,
      cases: [
        {
          id: "CASE-001A",
          description: "Office Supplies",
          weight: 45,
          totalWeight: 425.5,
          itemCount: 48,
          dimensions: { length: 24, width: 18, height: 12 },
          items: [
            {
              item_name: "Printer Paper (10-ream case)",
              quantity: 24,
              unit_weight: 15.5,
              total_weight: 372,
              dimensions_length: 12,
              dimensions_width: 8,
              dimensions_height: 10,
              volume: 5.56,
              condition: "Excellent",
              notes: "Sealed factory packaging",
              pallet_id: "PLT-001",
              case_id: "CASE-001A",
            },
            {
              item_name: "Ink Cartridge Set",
              quantity: 24,
              unit_weight: 2.2,
              total_weight: 52.8,
              dimensions_length: 4,
              dimensions_width: 2,
              dimensions_height: 6,
              volume: 0.28,
              condition: "Excellent",
              notes: "Compatible with HP LaserJet series",
              pallet_id: "PLT-001",
              case_id: "CASE-001A",
            },
          ],
        },
        {
          id: "CASE-001B",
          description: "First Aid Supplies",
          weight: 12,
          totalWeight: 187.0,
          itemCount: 36,
          dimensions: { length: 20, width: 16, height: 10 },
          items: [
            {
              item_name: "First Aid Kit (Large)",
              quantity: 12,
              unit_weight: 8.5,
              total_weight: 102,
              dimensions_length: 14,
              dimensions_width: 10,
              dimensions_height: 6,
              volume: 4.86,
              condition: "Excellent",
              notes: "OSHA compliant, 50-person capacity",
              pallet_id: "PLT-001",
              case_id: "CASE-001B",
            },
            {
              item_name: "Bandage Refill Pack",
              quantity: 24,
              unit_weight: 3.5,
              total_weight: 84,
              dimensions_length: 8,
              dimensions_width: 6,
              dimensions_height: 4,
              volume: 1.11,
              condition: "Excellent",
              notes: "",
              pallet_id: "PLT-001",
              case_id: "CASE-001B",
            },
          ],
        },
        {
          id: "CASE-001C",
          description: "Breakroom Supplies",
          weight: 8,
          totalWeight: 248.0,
          itemCount: 72,
          dimensions: { length: 22, width: 18, height: 14 },
          items: [
            {
              item_name: "Paper Towel Roll (12-pack)",
              quantity: 48,
              unit_weight: 0.5,
              total_weight: 24,
              dimensions_length: 6,
              dimensions_width: 4,
              dimensions_height: 1,
              volume: 0.14,
              condition: "Excellent",
              notes: "Individually wrapped",
              pallet_id: "PLT-001",
              case_id: "CASE-001C",
            },
            {
              item_name: "Coffee Pod Case (100-ct)",
              quantity: 24,
              unit_weight: 9.0,
              total_weight: 216,
              dimensions_length: 12,
              dimensions_width: 8,
              dimensions_height: 4,
              volume: 2.22,
              condition: "Good",
              notes: "Medium roast, single-serve",
              pallet_id: "PLT-001",
              case_id: "CASE-001C",
            },
          ],
        },
      ],
    },
    {
      id: "PLT-002",
      section: "B",
      totalWeight: 890.0,
      totalVolume: 35.6,
      itemCount: 84,
      cases: [
        {
          id: "CASE-002A",
          description: "Technology Equipment",
          weight: 22,
          totalWeight: 562.0,
          itemCount: 48,
          dimensions: { length: 24, width: 20, height: 16 },
          items: [
            {
              item_name: "Wireless Mouse (Box of 12)",
              quantity: 48,
              unit_weight: 11.25,
              total_weight: 540,
              dimensions_length: 16,
              dimensions_width: 12,
              dimensions_height: 8,
              volume: 8.89,
              condition: "Excellent",
              notes: "Logitech M510",
              pallet_id: "PLT-002",
              case_id: "CASE-002A",
            },
          ],
        },
        {
          id: "CASE-002B",
          description: "Power & Accessories",
          weight: 15,
          totalWeight: 328.0,
          itemCount: 36,
          dimensions: { length: 18, width: 14, height: 12 },
          items: [
            {
              item_name: "USB-C Hub (4-port)",
              quantity: 24,
              unit_weight: 1.5,
              total_weight: 36,
              dimensions_length: 8,
              dimensions_width: 2,
              dimensions_height: 2,
              volume: 0.19,
              condition: "Excellent",
              notes: "Supports 4K display output",
              pallet_id: "PLT-002",
              case_id: "CASE-002B",
            },
            {
              item_name: "Battery Pack (AA 48-ct)",
              quantity: 12,
              unit_weight: 2.8,
              total_weight: 33.6,
              dimensions_length: 6,
              dimensions_width: 4,
              dimensions_height: 3,
              volume: 0.42,
              condition: "Excellent",
              notes: "Alkaline, long-life",
              pallet_id: "PLT-002",
              case_id: "CASE-002B",
            },
          ],
        },
      ],
    },
    {
      id: "PLT-003",
      section: "C",
      totalWeight: 675.0,
      totalVolume: 28.4,
      itemCount: 62,
      cases: [
        {
          id: "CASE-003A",
          description: "Event Supplies",
          weight: 18,
          totalWeight: 425.0,
          itemCount: 32,
          dimensions: { length: 26, width: 20, height: 14 },
          items: [
            {
              item_name: "Tablecloth (6ft, White)",
              quantity: 16,
              unit_weight: 8.5,
              total_weight: 136,
              dimensions_length: 14,
              dimensions_width: 10,
              dimensions_height: 6,
              volume: 4.86,
              condition: "Excellent",
              notes: "Machine washable, polyester",
              pallet_id: "PLT-003",
              case_id: "CASE-003A",
            },
            {
              item_name: "Extension Cord (25ft)",
              quantity: 16,
              unit_weight: 4.5,
              total_weight: 72,
              dimensions_length: 8,
              dimensions_width: 8,
              dimensions_height: 4,
              volume: 1.48,
              condition: "Excellent",
              notes: "Heavy duty, 3-outlet",
              pallet_id: "PLT-003",
              case_id: "CASE-003A",
            },
          ],
        },
        {
          id: "CASE-003B",
          description: "Cleaning Supplies",
          weight: 10,
          totalWeight: 250.0,
          itemCount: 30,
          dimensions: { length: 20, width: 16, height: 10 },
          items: [
            {
              item_name: "Sanitizing Wipes (Canister)",
              quantity: 30,
              unit_weight: 8.0,
              total_weight: 240,
              dimensions_length: 10,
              dimensions_width: 6,
              dimensions_height: 4,
              volume: 1.39,
              condition: "Excellent",
              notes: "75 wipes per canister",
              pallet_id: "PLT-003",
              case_id: "CASE-003B",
            },
          ],
        },
      ],
    },
  ],
};

// Calculate totals from sample data
export const getSampleTotals = () => {
  let totalWeight = 0;
  let totalVolume = 0;
  let totalItems = 0;
  let totalCases = 0;

  SAMPLE_SHIPMENT.pallets.forEach(pallet => {
    totalWeight += pallet.totalWeight;
    totalVolume += pallet.totalVolume;
    totalItems += pallet.itemCount;
    totalCases += pallet.cases.length;
  });

  return {
    totalWeight,
    totalVolume,
    totalItems,
    totalPallets: SAMPLE_SHIPMENT.pallets.length,
    totalCases,
  };
};
