// This file is automatically generated. Do not edit it directly,
// except for the security comments below which document storage policy.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

/**
 * SECURITY NOTE — Auth token storage
 * ------------------------------------------------------------------
 * Auth tokens are persisted in browser `localStorage`. This is the
 * Supabase JS default and is required because the app is a static SPA
 * with no first-party backend to set HttpOnly cookies.
 *
 * Risks: XSS attacks could exfiltrate the access token. We mitigate
 * via strict React rendering (no dangerouslySetInnerHTML on user data),
 * CSP planning, and short Supabase access-token lifetimes.
 *
 * Migration plan: move sessions to HttpOnly cookies via an auth proxy.
 * See `docs/security/http-only-cookie-session-migration.md`.
 *
 * Do NOT manually read `localStorage[...auth-token]` anywhere in app
 * code, and never log session/access tokens. Use `supabase.auth.*`.
 */
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: brokeredPreviewStorage(),
    persistSession: true,
    autoRefreshToken: true,
  }
});